# Generated by Django 3.0.3 on 2020-08-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_category_influencer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
