# Generated by Django 3.0.3 on 2020-08-20 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20200820_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencers', to='basic_app.Category'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
