# Generated by Django 3.0.3 on 2020-08-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20200820_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descripion',
            new_name='description',
        ),
    ]
