# Generated by Django 3.0.3 on 2020-08-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20200820_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='instahandle',
            field=models.CharField(default=2, max_length=256),
            preserve_default=False,
        ),
    ]
