# Generated by Django 3.0.3 on 2020-08-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_influencer_instahandle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencer',
            old_name='instahandle',
            new_name='link',
        ),
    ]
