# Generated by Django 3.0.3 on 2020-08-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0011_auto_20200827_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Race',
        ),
    ]
