# Generated by Django 3.0.3 on 2020-08-27 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0013_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='race',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='races', to='basic_app.Race'),
        ),
    ]
