# Generated by Django 3.0.3 on 2020-08-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0016_auto_20200827_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
