# Generated by Django 3.0.3 on 2020-08-28 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0020_auto_20200828_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='gender',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='genders', to='basic_app.Gender'),
        ),
    ]
