# Generated by Django 3.0.3 on 2020-08-28 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0022_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influencers', to='basic_app.Location'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(blank=True, default='1', max_length=256),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='delivery',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='email',
            field=models.EmailField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influencers', to='basic_app.Gender'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influencers', to='basic_app.Race'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='surname',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, default='1', max_length=256),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(blank=True, default='1', max_length=256),
        ),
    ]
