# Generated by Django 3.0.3 on 2020-08-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0023_auto_20200828_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(default='1', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='1', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(default='1', max_length=256, null=True),
        ),
    ]
