# Generated by Django 3.0.3 on 2020-08-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0028_auto_20200828_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(blank=True, default='1', max_length=256),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, default='1', max_length=256),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(blank=True, default='1', max_length=256),
        ),
    ]
