# Generated by Django 3.0.3 on 2020-08-28 13:50

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0030_auto_20200828_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', multiselectfield.db.fields.MultiSelectField(choices=[('a', 'Wine'), ('b', 'Food'), ('c', 'Lifestyle'), ('d', 'Food'), ('e', 'Recipes'), ('f', 'Vegan'), ('g', 'Parenting '), ('h', 'Baby'), ('h', 'Cat'), ('h', 'Dog ')], max_length=11)),
            ],
        ),
    ]
