# Generated by Django 3.0.3 on 2020-08-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0031_multicategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultiCategory',
        ),
    ]
