# Generated by Django 3.0.3 on 2020-08-29 08:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0032_delete_multicategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Wine'), (2, 'Lifesttyle'), (3, 'Food'), (4, 'Recipes'), (5, 'Vegan'), (6, 'Parenting'), (7, 'Baby'), (8, 'Cat'), (9, 'Dog')], default=1, max_length=17),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
