# Generated by Django 3.0.3 on 2020-08-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0034_auto_20200830_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='category',
            field=models.ManyToManyField(related_name='influencers', to='basic_app.Category'),
        ),
    ]
